language: ruby
rvm:
  - 1.9.2
env:
  - DISPLAY=:99.0
before_install: sh -e /etc/init.d/xvfb start
notifications:
  irc:
    channels:
      - "irc.freenode.org#civicworks"
    on_success: change
    on_failure: always
  email: false
branches:
  only:
    - master